#### ARRAYS

- An array is an object that stores a group of elements of same datatypes.
- If it is of same datatype , then it proesses things very fast.

- Array can store only on type of data . Either we can only store integer type data or float type data into an array.
- Arrays can increase of decrease their size dynamically . 

arr1=[1,2,3,4,5, ....... 1000000items]

#### Advantages of Arrays
- Arrays are similar tolists , arrays can only store same type of elements . Arrays uses less memory than lists and they are faster 
- Arrays are useful to handle a collection of elements which are simmilar

In [18]:
#help()

In [3]:
import numpy as np

In [76]:
a=np.array(['a','b','c','d'])
print(a)
type(a)

['a' 'b' 'c' 'd']


numpy.ndarray

In [8]:
n=len(a)

i=0
while i<n:
    print(a[i],end=' ')
    i=i+1

a b c d 

In [153]:
arr1=np.array([1.5,2.5,-4,12,232,4232,12,2323,21,1.5])
arr1[4:7]

array([ 232., 4232.,   12.])

In [154]:
arr1[-7:-2]

array([  12.,  232., 4232.,   12., 2323.])

#### Methods in Arrays : 

In [11]:
# append

arr1=np.array([1,2,-4,12,232,42,52,251,1000])
arr2 = np.append(arr1,1000)
arr2

array([   1,    2,   -4,   12,  232,   42,   52,  251, 1000, 1000])

In [12]:
# count
arr2 = np.count_nonzero(arr2==1000)
arr2

2

In [13]:
# Concatenate two arrays

a = np. array([1,2])
b= np.array([3,4])
c = np.concatenate([a,b])
print(c)

[1 2 3 4]


In [14]:
# Index

np.where(c==4)

(array([3], dtype=int64),)

In [15]:
# Insert at certian position

d = np.insert(c,0,0)
d

array([0, 1, 2, 3, 4])

In [16]:
# Delete

arr2 = np.array([1,2,4,6,7,7,5,336,3])
np.delete(arr2,7) # 7th position

array([1, 2, 4, 6, 7, 7, 5, 3])

In [17]:
# Unique - No duplicate

arr2 = np.array([1,2,4,6,7,7,5,336,3])
np.unique(arr2) # No Duplicate

array([  1,   2,   3,   4,   5,   6,   7, 336])

In [18]:
arr2 = np.array([1,2,4,6,7,7,5,336,3])
np.flip(arr2) 

array([  3, 336,   5,   7,   7,   6,   4,   2,   1])

#### Types of arrays 

- Single dimension arrays  # kind of one column in a data frame 
- Multi- dimension arrays # when you have more than one rows and more than one column of elements

In [19]:
#multidimension arrays :
marks=np.array([[50,60,70,66,72],    #first row talks about 1st student marks in Maths , Physic  , Chemisty , History , Science
             [60,62,78,232,12],
             [55,232,242,123,12]])  # We have 3 rows and 5 columns

#### Creating arrays in numpy can be done in several ways 
- 1) array() function 
- 2) linespace()   ==> linespace(start,stop,n)
- 3) logspace()  ==> produced equal spaced points ..but on logarithmic scale
- 4) arange()
- 5) zeroes() and ones()

In [23]:
a=np.linspace(0,10,5)
print("a= ",a)

a=  [ 0.   2.5  5.   7.5 10. ]


In [26]:
a1=np.logspace(1,4,5) # 10^1 to 10^4  and you divide all those values into 5 equal part
print(a1)
for i in range(len(a1)):
    print(a1[i],end='  ')

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]
10.0  56.23413251903491  316.22776601683796  1778.2794100389228  10000.0  

In [28]:
np.arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [6]:
np.ones(6,float)

array([1., 1., 1., 1., 1., 1.])

In [35]:
arr1=np.array([120,123,231,244,1232])
arr_1=arr1+100
print(arr_1)

[ 220  223  331  344 1332]


In [36]:
arr1=np.array([120,123,231,244,1232])
arr_1=arr1*100
print(arr_1)

[ 12000  12300  23100  24400 123200]


#### Mathematical Functions in Numpy

In [35]:
arr1=np.array([120,123,231,244,123])
print(np.sin(arr1))
print(np.cos(arr1))
print(np.sum(arr1))
print(np.prod(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.cov(arr1))
print(np.std(arr1))
print(np.mean(arr1))
print(np.sort(arr1))
print(np.var(arr1))

[ 0.58061118 -0.45990349 -0.99568419 -0.8645363  -0.45990349]
[ 0.81418097 -0.88796891  0.09280622  0.50257038 -0.88796891]
841
-751500384
120
244
3
0
4024.7
56.74292907490765
168.2
[120 123 123 231 244]
3219.76


#### Operations 

In [155]:
arr2 = np.array([12,23,45,45,32])
arr2
print(arr2**2)
print(arr2+20)
print(arr2-12)
print(arr2/2)
print(arr2*12)

[ 144  529 2025 2025 1024]
[32 43 65 65 52]
[ 0 11 33 33 20]
[ 6.  11.5 22.5 22.5 16. ]
[144 276 540 540 384]


#### Comparison Array

In [54]:
arr1 = np.array([12,12,45,42,36])
arr2 = np.array([12,23,45,45,32])
arr1>=arr2

array([ True, False,  True, False,  True])

In [56]:
a= np.array([10,20,30])
b= np.array([30,40,50])
a>b

array([False, False, False])

In [58]:
# any : if any ONE element of the array is True
# all ? : whether  alll the elements in array are True 

In [59]:
a= np.array([100,20,30])
b= np.array([30,40,50])
c=a>b
print("resylts of a>b ",c)
print("check if any one element is true :",any(c))
print("check if all the elemets are true :" ,all(c))

resylts of a>b  [ True False False]
check if any one element is true : True
check if all the elemets are true : False


#### Aliasing 

In [63]:
a=np.array([1,2,3,0])
b=a # Aliasing 
print(b)
b[0]=99
print(a) # to avoid this we should create copy of a, so any change in variable b won't affect a as well. 

[1 2 3 0]
[99  2  3  0]


In [65]:
a=np.array([1,2,3,0])
b=a.copy()
b[0]=99  # modfying b 
print('Original array',a)
print("New array ", b)

Original array [1 2 3 0]
New array  [99  2  3  0]


#### Reshaping the Arrays

In [88]:
arr1=np.arange(10)
print(arr1)
arr2=np.reshape(arr1,(5,2)) # 5 rows and 1 column
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [92]:
# Flatten : it is used to return a copy of array collapsed in one dimension 
arr2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# how do we create multidimensional arrays
# Any 2 D array is also called Matrix : 
# Matrix with m rows and n columns is called m * n matrix

In [95]:
# one Dimensions of arrays :
arr1=np.array([1,
            2,
            3,
            4,
            5])
print(arr1)
arr1[3]

[1 2 3 4 5]


4

In [96]:
# 2 dimension arrays : anything whihc have more than 1 row and 1 column 
arr2=np.array([ [1,2,3],
             [4,5,6]])
print(arr2)  # we have two rows and 3 columns 
arr2[1][2]   # 1 row 

[[1 2 3]
 [4 5 6]]


6

In [108]:
print(np.shape(arr2))
print(np.size(arr2))
print(np.ndim(arr2))
print(len(arr2))

(2, 3)
6
2
2


In [114]:
# 3 dimension arrays : # 2 arrays , 3 rows and 2 columns
a = np.arange(12)
b=np.reshape(a,(2,3,2))  # 2 arrays , 3 rows and 2 columns
print(b)
print(b[1][2][1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
11


In [101]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [102]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [104]:
e=np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Matrix - We can create matrix in array

In [158]:
a1=[[1,2,3] , [4,5,6]]
print(type(a1))
a2=np.matrix(a1)
a2

<class 'list'>


matrix([[1, 2, 3],
        [4, 5, 6]])

In [117]:
str1="1 2;3 4;5 6"
b2=np.matrix(str1)
b2

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [144]:
a1=np.matrix([[1,2,3] , [4,5,6]])
a2 = a1*10
a2

matrix([[10, 20, 30],
        [40, 50, 60]])

In [125]:
# Sort the matrix :
m=np.matrix([[5,4,1] , [2,7,0]])
print(m)
m2=np.sort(m,axis=1) # 0 is for columns and 1 for sorting on rows
print(m2)
m3=np.sort(m2,axis=0) # 0 is for columns and 1 for sorting on rows
print(m3)

[[5 4 1]
 [2 7 0]]
[[1 4 5]
 [0 2 7]]
[[0 2 5]
 [1 4 7]]


In [127]:
# Transpose of matrix - convert column into row
m=np.matrix([[5,4,1] , [2,7,0]])
np.transpose(m)

matrix([[5, 2],
        [4, 7],
        [1, 0]])

#### Random Numbers 

In [146]:
np.random.rand()

0.2828306637590925

In [147]:
np.random.rand(5)

array([0.0329379 , 0.75814837, 0.1127004 , 0.75457941, 0.14987086])

In [148]:
np.random.rand(2,3)

array([[0.03827169, 0.12748582, 0.28559602],
       [0.31975767, 0.67783384, 0.84023908]])

In [149]:
np.random.random()

0.8769194303472152